# Generated by Django 5.0.4 on 2024-09-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_educatorupload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="educatorupload",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/img/"),
        ),
        migrations.AlterField(
            model_name="educatorupload",
            name="ppt_file",
            field=models.FileField(upload_to="uploads/ppt/"),
        ),
    ]
