# Generated by Django 5.0.4 on 2024-09-20 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_educatorupload_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_at', models.DateTimeField(auto_now_add=True)),
                ('educator_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.educatorupload')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
