# Generated by Django 5.0.4 on 2024-09-21 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
